Server:
  Mode: dev #production release
  Port: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  PageSize: 10
  Limit: 100
  LogFileName: "storage/web_app.log"
  MaxSize: 200
  MaxAge: 30
  MaxBackups: 7
DataBase:
  Type: mysql
  User: root
  Password: 1234567
  Host: 127.0.0.1
  Port: 3306
  TableName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30




