Server:
  Mode: debug #production release
  Port: 8080
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  PageSize: 10
  Limit: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
DataBase:
  Type: mysql
  User: root
  Password: 1234567
  Host: 127.0.0.1
  Port: 3306
  TableName: xxx
  TablePrefix: xxx_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30




